name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 11
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Lint
        run: pnpm lint
      
      - name: Typecheck
        run: pnpm typecheck
      
      - name: Prisma Validate
        run: pnpm prisma:validate
      
      - name: Test
        run: pnpm test
      
      - name: Build API
        run: pnpm build:api
      
      - name: Build Web
        run: pnpm build:web
